<a href="https://colab.research.google.com/github/alexanderBrena98/trabajos_Python/blob/main/Bre%C3%B1a_Vel%C3%A1squez_Jes%C3%BAs_Alexander_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## EJERCICIO

### Ejercicio 1: Creación y Manipulación de Arreglos

1. Crea un arreglo unidimensional que contenga los números del 1 al 10.
2. Crea un arreglo bidimensional de forma \(3 \times 3\) con números del 1 al 9.
3. Utiliza el método `reshape` para convertir el arreglo unidimensional del punto 1 en un arreglo bidimensional de forma \(2 \times 5\).

In [ ]:
#Ejercicio 1
# 1
import numpy as np

arr =np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2

array1 = np.arange(1,4)
array2 = np.arange(4,7)
array3 = np.arange(7,10)
print(array1)
print(array2)
print(array3)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
#3
arr = np.arange(1,11)
print("Array Original : ",arr,"\n")


matriz = arr.reshape(2, 5)
print("Matriz:")
print(matriz,"\n")

Array Original :  [ 1  2  3  4  5  6  7  8  9 10] 

Matriz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 




### Ejercicio 2: Indexación y Slicing

Dado el arreglo bidimensional:


\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}


Realiza las siguientes operaciones:

1. Extrae el número 5 de la matriz.
2. Obtén la primera fila.
3. Obtén la última columna.
4. Utiliza slicing para obtener la submatriz
\begin{pmatrix} 5 & 6 \\ 8 & 9 \end{pmatrix}

In [ ]:
#1
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Extracción del número 5:",array[1][1],"\n")
#2
print("Primera Fila:", array[0],"\n")
#3
print("Última Columna")
print(array[0:3,2:3])
print("\n")
#4
print("Submatriz")
print(array[1:3,1:3])
print("\n")

Extracción del número 5: 5 

Primera Fila: [1 2 3] 

Última Columna
[[3]
 [6]
 [9]]


Submatriz
[[5 6]
 [8 9]]





### Ejercicio 3: Operaciones Matemáticas

1. Crea dos arreglos unidimensionales \( A \) y \( B \) de la misma longitud, llenos de números aleatorios.
2. Calcula la suma \( A + B \).
3. Calcula el producto punto \( A \cdot B \).
4. Encuentra el valor máximo en el arreglo \( A + B \) y su correspondiente índice.

Estos ejercicios cubren las operaciones básicas de NumPy y deberían proporcionar una buena práctica para los estudiantes que están empezando.

In [ ]:
#1
import numpy as np

a = np.random.randint(1,20,10)
b = np.random.randint(1,20,10)
print(a)
print(b)
print("\n")
#2
sum= a+b
print("La suma de matrices es:",sum)
print("\n")
#3
multi=a*b
print("El producto de las matrices es:",multi)
print("\n")
#4
print("El máximo valor del arreglo a+b es:",sum.max())

indice = np.where(sum == sum.max())
print(f'Posición sum_max:{indice}')

[ 4 18  2  6 11  3 16 15 15  8]
[10 18 16  5  2  5  2  8 12 15]


La suma de matrices es: [14 36 18 11 13  8 18 23 27 23]


El producto de las matrices es: [ 40 324  32  30  22  15  32 120 180 120]


El máximo valor del arreglo a+b es: 36
Posición sum_max:(array([1]),)
